groups:
  - name: alerts
    rules:
      # приложение не работает
      - alert: ServiceDown
        expr: up{job='sample_monitoring'} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Сервис {{ $labels.instance }} недоступен больше 1 минуты"

      - alert: 1kMoreRequestAlert
        expr: sum(rate(http_server_requests_seconds_count[1m])) > 1000
        for: 0s
        labels:
          severity: info
        annotations:
          summary: "Приложение получает запросы"
          description: "Нагрузка: {{ $value | printf \"%.2f\" }} RPS"

      - alert: HighRequestLatency
        expr: rate(http_server_requests_seconds_sum[1m]) / rate(http_server_requests_seconds_count[1m]) > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Высокая задержка API"
          description: "Среднее время ответа API > 0.5 сек за последнюю минуту"

      - alert: HighCpuUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Высокая загрузка CPU"
          description: "CPU > 80% на {{ $labels.instance }}"
